# Generated by Django 4.2.11 on 2024-03-28 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('call_duration', models.IntegerField()),
                ('call_type', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('week', models.CharField(max_length=20)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.phonenumber')),
            ],
        ),
    ]
